import createClient from "openapi-fetch"
import type { paths } from "@/models/__generated__/schema" // generated by openapi-typescript

const client = createClient<paths>({
  baseUrl: process.env.NEXT_PUBLIC_API_URL,
})

export default client
