import FirestoreCollections from "../adapters/FirestoreCollections"
import { Reagent } from "../../business-layer/models/Reagent"
import { ReagentCategory } from "business-layer/models/Reagent"
import { Timestamp } from "firebase-admin/firestore"

export class BountyService {
  /**
   * Get all wanted reagents from the database.
   *
   * @returns Promise<Reagent[]> - An array of all wanted reagents posted by users.
   */
  async getAllWantedReagents(): Promise<Reagent[]> {
    const wantedSnapshot = await FirestoreCollections.wanted.get()
    return wantedSnapshot.docs.map((doc) => {
      const data = doc.data()
      return { id: doc.id, ...data } as Reagent
    })
  }

  /**
   * Get a wanted reagent by its ID.
   *
   * @param id - The ID of the wanted reagent to retrieve.
   * @returns Promise<Reagent | null> - The wanted reagent if found, otherwise null.
   */
  async getWantedReagentById(id: string): Promise<Reagent | null> {
    const wantedSnapshot = await FirestoreCollections.wanted.doc(id).get()
    if (!wantedSnapshot.exists) {
      return null
    }
    return wantedSnapshot.data()
  }

  /**
   * Get wanted reagents by its categories
   *
   * @param categories - The category of the wanted reagent to retrive.
   * returns Promise<Reagent[]> - Returns an array of reagents.
   */
  async getWantedReagentsByCategory(
    categories: ReagentCategory[],
  ): Promise<Reagent[]> {
    const wantedSnapshot = await FirestoreCollections.wanted
      .where("categories", "array-contains-any", categories)
      .get()
    return wantedSnapshot.docs.map((doc) => doc.data())
  }

  /**
   * Get wanted reagents by its owner from the Firestore database.
   *
   * @param user_id - The user id used to get thier wanted reagents.
   * @returns Promise<Reagent[]> - Returns an array of reagents.
   */
  async getWantedReagentsByUserId(user_id: string): Promise<Reagent[]> {
    const wantedSnapshot = await FirestoreCollections.wanted
      .where("user_id", "==", user_id)
      .get()
    return wantedSnapshot.docs.map((doc) => doc.data())
  }

  /**
   
Creates a new wanted reagent in the Firestore database.*
@params newWanted - the wanted reagent to create.
@returns Reagent - Returns the created wanted reagent with its ID generated by firebase*/

  async createWanted(
    newWanted: Omit<Reagent, "createdAt" | "createdAtReadable" | "id">,
  ): Promise<Reagent & { id: string }> {
    const createdAt = Timestamp.now().toDate().toISOString()
    const createdAtReadable = new Date().toISOString().split("T")[0]
    const docRef = await FirestoreCollections.wanted.add({
      ...newWanted,
      createdAt,
      createdAtReadable,
    })
    const result = {
      ...newWanted,
      id: docRef.id,
      createdAt,
      createdAtReadable,
    }
    return result
  }

  /**
   * Deletes a wanted reagent from the Firestore database.
   *
   * @param id - The ID of the wanted reagent to delete.
   * @returns Wanted - Returns the deleted reagent as a ref.
   */
  async deletedReagent(id: string): Promise<Reagent> {
    try {
      const docRef = await FirestoreCollections.wanted.doc(id)
      if (docRef == null) {
        throw new Error(`Reagent - ${id} not found`)
      }
      const wanted = (await docRef.get()).data() as Reagent
      await docRef.delete()
      return wanted
    } catch (err) {
      console.log(err)
      throw new Error(`Failed to delete wanted reagent - ${id}:${err}`)
    }
  }

  /**
   * Updates wanted reagent info in the Firestore database.
   *
   * @params id - The ID of the reagent to update.
   * @params update - The update to apply to the reagent.
   * @returns Wanted - Returns the wanted reagent.
   */

  async updateReagent(id: string, update: Partial<Reagent>): Promise<Reagent> {
    try {
      const docRef = await FirestoreCollections.wanted.doc(id)
      const snapShot = await docRef.get()
      if (!snapShot.exists) {
        throw new Error(`Reagent - ${id} not found`)
      }
      const { user_id, ...SafeUpdate } = update
      console.log(`User updating wanted reagent - ${id}`, user_id)
      await docRef.update(SafeUpdate)
      const updatedDoc = await docRef.get()
      return updatedDoc.data() as Reagent
    } catch (err) {
      console.log(err)
      throw new Error(`Failed to update wanted reagent - ${id}: ${err}`)
    }
  }
  /**
   * Delete a wanted reagent by its offered reagent ID.
   */
  async deleteBountiesByOfferedReagentId(
    offeredReagentId: string,
  ): Promise<void> {
    try {
      const wantedSnapshot = await FirestoreCollections.wanted
        .where("requesterOfferedReagentId", "==", offeredReagentId)
        .get()
      const deletePromises = wantedSnapshot.docs.map((doc) => doc.ref.delete())
      await Promise.all(deletePromises)
    } catch (err) {
      console.log(err)
      throw new Error(
        `Failed to delete wanted reagents - ${offeredReagentId}: ${err}`,
      )
    }
  }
}
