export const USERS_COLLECTION = "users"
export const REAGENTS_COLLECTION = "reagents"
export const ORDERS_COLLECTION = "orders"
export const CHAT_ROOMS_COLLECTION = "chat_rooms"
export const MESSAGES_COLLECTION = "messages"
