export const USERS_COLLECTION = "users"
export const REAGENTS_COLLECTION = "reagents"
export const ORDERS_COLLECTION = "orders"
export const CHAT_ROOMS_COLLECTION = "chat_rooms"
export const MESSAGES_COLLECTION = "messages"
export const AUTH_DOMAINS_COLLECTION = "auth_domains"
export const WANTED_COLLECTION = "wanted"
export const OFFERS_COLLECTION = "offers"
